import { execFile } from 'child_process';
import { mkdtemp, readFile, readdir, rm } from 'fs/promises';
import { basename, dirname, join } from 'path';
import { tmpdir } from 'os';
import { promisify } from 'util';
import { AdapterError, ErrorCode } from '../../errors.js';
import { CONFIG } from '../../utils/config.js';

const execFileAsync = promisify(execFile);

export async function exportDslToJson(dslPath: string): Promise<unknown> {
  const tmpDir = await mkdtemp(join(tmpdir(), 'erode-structurizr-'));

  try {
    const cliPath = CONFIG.adapter.structurizr.cliPath;
    const dslDir = dirname(dslPath);
    const dslBasename = basename(dslPath);

    if (cliPath) {
      // Use local WAR file
      try {
        await execFileAsync('java', [
          '-jar',
          cliPath,
          'export',
          '-workspace',
          dslPath,
          '-format',
          'json',
          '-output',
          tmpDir,
        ]);
      } catch (error) {
        if (isEnoentError(error)) {
          throw new AdapterError(
            'Java or Structurizr not found',
            ErrorCode.MODEL_LOAD_ERROR,
            'structurizr',
            'Could not run Structurizr export',
            { cliPath },
            getInstallSuggestions()
          );
        }
        throw error;
      }
    } else {
      // Use Docker
      try {
        await execFileAsync('docker', [
          'run',
          '--rm',
          '-v',
          `${dslDir}:/workspace`,
          '-v',
          `${tmpDir}:/output`,
          'structurizr/structurizr:2026.02.01',
          'export',
          '-workspace',
          `/workspace/${dslBasename}`,
          '-format',
          'json',
          '-output',
          '/output',
        ]);
      } catch (error) {
        if (isEnoentError(error)) {
          throw new AdapterError(
            'Docker not found',
            ErrorCode.MODEL_LOAD_ERROR,
            'structurizr',
            'Could not run Structurizr export via Docker',
            {},
            getInstallSuggestions()
          );
        }
        throw error;
      }
    }

    // Find and read the JSON file
    const files = await readdir(tmpDir);
    const jsonFile = files.find((f) => f.endsWith('.json'));

    if (!jsonFile) {
      throw new AdapterError(
        'No JSON file generated by Structurizr',
        ErrorCode.MODEL_LOAD_ERROR,
        'structurizr',
        'Structurizr export did not produce a JSON file'
      );
    }

    const jsonPath = join(tmpDir, jsonFile);
    const content = await readFile(jsonPath, 'utf-8');
    return JSON.parse(content);
  } finally {
    await rm(tmpDir, { recursive: true, force: true });
  }
}

function isEnoentError(error: unknown): boolean {
  if (error instanceof Error) {
    return 'code' in error && error.code === 'ENOENT';
  }
  return false;
}

function getInstallSuggestions(): string[] {
  return [
    'Set STRUCTURIZR_CLI_PATH to the path of the Structurizr WAR file',
    'Or install Docker and pull the structurizr/structurizr image',
    'Or pre-export your workspace to JSON: java -jar structurizr.war export -workspace workspace.dsl -format json',
  ];
}
